config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    root 'books#index'
    devise_for :user
    resources :books, except: :destroy
    resources :reservations, except: :destroy
    resources :users, only: %i[new create show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :nullify

  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  # Um livro pertence a um autor e a uma categoria,
  # e possui reservas, mas apenas uma deve estar ativa
  belongs_to :author
  belongs_to :category
  has_many :reservations, dependent: :nullify
  has_many :active_reservations, -> { where(status: :active) },
           class_name: 'Reservation', inverse_of: :book

  has_one_attached :cover

  validates :title, presence: true

  def reserved?
    active_reservations.present?
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :book
  belongs_to :user

  # Reservas com devolução atrasada
  scope :overdue, -> { where(status: 'active', devolution: ...DateTime.now) }
  scope :active, -> { where(status: 'active') }
  scope :finished, -> { where(status: 'finished') }

  # A reserva pode estar ativa, atrasada, ou finalizada
  enum status: { active: 0, finished: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are: :registerable,
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Usuários não podem se registrar, um admin deve registrá-los.
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # o usuário possui reservas
  has_many :reservations, dependent: :nullify

  scope :member, -> { where(role: :member) }

  validates :name, :role, presence: true

  # adiciona tipo de usuário
  enum role: { admin: 0, member: 1 }, _suffix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Callback para verificar se usuário é admin
  def authorize_admin
    return if current_user.admin_role?

    redirect_to root_path, alert: t('authorize_role_message')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  # Verifica se usuário é admin
  before_action :authorize_admin, only: %i[new create edit]

  def index
    @books = Book.includes(:active_reservations, :author, :category)
                 .order(:created_at).page(params[:page]).per(12)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
  end

  def create
    @book = Book.new(book_params)
    redirect_to @book, notice: t('.success') if @book.save
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to @book, notice: t('.success') if @book.save
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_id, :category_id, :cover)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  # Verifica se usuário é admin
  before_action :authorize_admin, only: %i[edit]

  def index
    @reservations = reservation_scope.page(params[:page]).per(12)
  end

  def show
    @reservation = reservation_scope.find(params[:id])
  end

  def new
    @reservation = reservation_scope.new
    @book = Book.find(params[:book_id])
  end

  def create
    @reservation = reservation_scope.new(reservation_params)
    @reservation.user = current_user if current_user.member_role?
    return unless @reservation.save

    @reservation.active!
    redirect_to @reservation, notice: t('.success')
  end

  def edit
    @reservation = reservation_scope.find(params[:id])
    @book = @reservation.book
  end

  def update
    @reservation = reservation_scope.find(params[:id])
    @reservation.update(reservation_params_update)
    redirect_to @reservation, notice: t('.success') if @reservation.save
  end

  private

  def reservation_params
    params.require(:reservation).permit(:book_id, :user_id, :devolution)
  end

  def reservation_params_update
    params.require(:reservation).permit(:devolution, :status)
  end

  # Se o usuário for admin, pode buscar por todas as reservas, mas se for membro,
  # poderá buscar apenas pelas suas reservas
  def reservation_scope
    if current_user.admin_role?
      Reservation
    else
      current_user.reservations
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :authorize_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    redirect_to @user, notice: t('.success') if @user.save
  end

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def book_cover(book)
    cover = book.cover.attached? ? book.cover : 'no-cover.jpg'
    image_tag(cover, width: '100%')
  end

  def book_admin_links(book)
    link_to('Editar', edit_book_path(book), class: 'btn btn-primary', style: 'margin-left: 5px;')
    .concat(
      if book.active_reservations.blank?
        link_to('Criar nova reserva', new_reservation_path(params: { book_id: book.id }),
                class: 'btn btn-primary')
      end
    )
  end

  def book_member_links(book)
    if book.active_reservations.blank?
      link_to 'Reservar', new_reservation_path(params: { book_id: book.id }),
              class: 'btn btn-primary'
    else
      content_tag(:div, 'O livro não está disponível no momento', class: 'hint')
    end
  end
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.association :author, collection: Author.all.order(:name) %>
  <%= f.association :category, collection: Category.all.order(:name)  %>
  <%= f.input :cover %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<% @books.each_slice(4) do |books| %>
  <div class="row">
    <% books.each do |book| %>
      <div class="col-md card" style="margin: 10px;">
        <%= link_to book_cover(book), book %>
        <div class="card-body">
          <h5 class="card-title"><%= book.title %></h5>
          <p class="card-text">
            Autor: <%= book.author.name %> <br>
            Categoria: <%= book.category.name %> <br>
            Status: <%= book.reserved? ? 'Reservado' : 'Disponível' %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= paginate @books %>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <%= book_cover(@book) %>
    </div>
    <div class="col-md-8">
      <p>Título: <%= @book.title %></p>
      <p>Autor: <%= @book.author.name %></p>
      <p>Categoria: <%= @book.category.name %></p>

      <%= book_admin_links(@book) if current_user.admin_role? %>
      <%= book_member_links(@book) if current_user.member_role? %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Library</a>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Página Inicial</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Ver reservas', reservations_path, class: 'nav-link' %>
          </li>
          <% if current_user&.admin_role? %>
            <li class="nav-item">
              <%= link_to 'Cadastrar novo livro', new_book_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Cadastrar novo usuário', new_user_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav ms-auto">
            <li class="nav-item">
              <span class="nav-link"><%= current_user.name %> (<%= current_user.role %>)</span>
            </li> 
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link' %>
            </li>
        </ul>
      </div>
    <% end %>
  </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <section class="py-5 text-center container">
      <%= yield %>
    </section>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= simple_form_for @reservation do |f| %>
  <%= f.association :book, selected: @book.id,
                           collection: [@book],
                           input_html: { value: params[:book_id] } %>
  <%= f.association :user, selected: current_user, collection: [current_user] if current_user.member_role? %>
  <%= f.association :user, collection: User.member if current_user.admin_role? %>
  <%= f.input :status, collection: Reservation.statuses.keys if current_user.admin_role? && !@reservation.new_record? %>
  <%= f.input :devolution, as: :date, html5: true %>
  <%= f.button :submit %>
<% end %>

app/views/reservations/edit.html.erb
<%= render 'form' %>

app/views/reservations/index.html.erb
<% return if @reservations.blank? %>
<% @reservations.each_slice(4) do |reservations| %>
  <div class="row">
    <% reservations.each do |r| %>
      <div class="col-md card" style="margin: 10px; max-width:250px;">
        <%= link_to book_cover(r.book), reservation_path(r) %>
        <div class="card-body">
          <h5 class="card-title"><%= r.book.title %></h5>
          <p class="card-text">
            Usuário: <%= r.user.name %><br>
            Devolução: <%= r.devolution %><br>
            Status: <%= r.status %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= paginate @reservations %>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <%= link_to book_cover(@reservation.book), @reservation.book %>
    </div>
    <div class="col-md-8">
      <p>Usuário: <%= link_to @reservation.user.name, user_path(@reservation.user) %></p>
      <p>Devolução: <%= @reservation.devolution %></p>
      <p>Status: <%= @reservation.status %></p>

      <%= link_to 'Editar', edit_reservation_path(@reservation), class: 'btn btn-primary' if current_user.admin_role? %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :role, collection: User.roles.keys %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h5><%= @user.name %> (<%= @user.role %>)</h5>
<p>E-mail: <%= @user.email %></p>
<p>Cadastrado em: <%= @user.created_at %></p>
<% if @user.member_role? %>
  <h4>Reservas</h4>
  <%# filtrar  %>
  <% @user.reservations.each do |r| %>
    <p><%= link_to "Id: #{r.id}, Devolução: #{r.devolution.strftime('%d/%m/%Y')}, Status: #{r.status}", reservation_path(r) %></p>
  <% end %>
<% end %>